spring.application.name=artefacto

# R2DBC configuration for PostgreSQL (reactive)
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/enterprise
spring.r2dbc.username=postgres
spring.r2dbc.password=zayro

# Optional: initialize schema from classpath (disabled by default)
spring.sql.init.mode=never
