server.port=8002


# IDENTITY (ContextIdApplicationContextInitializer)
spring.application.name=artefacto
 
# LOGGING
logging.level.root=INFO
logging.level.com.rest.api=DEBUG

# DEVTOOLS (DevToolsProperties)
# enable automatic restart
spring.devtools.restart.enabled=true

# ENDPOINTS CORS CONFIGURATION (MvcEndpointCorsProperties)


# SECURITY (SecurityProperties)
security.basic.enabled=true