spring.application.name=artefacto
spring.sql.init.mode=never
spring.r2dbc.pool.enabled=true
spring.r2dbc.url=${DB_R2DBC_URL:r2dbc:postgresql://localhost:5432/enterprise}
spring.r2dbc.username=${DB_USERNAME:postgres}
spring.r2dbc.password=${DB_PASSWORD:zayro}

# Default profile for local development; override to prod in deployment.
spring.profiles.active=dev
