spring.application.name=artefacto

# SPRING CONFIG (ConfigFileApplicationListener)
## config file name (default to 'application')
spring.config.name=app 

# Database configuration
spring.sql.init.mode=never
spring.r2dbc.pool.enabled=true
spring.r2dbc.url=${DB_R2DBC_URL:r2dbc:postgresql://localhost:5432/enterprise}
spring.r2dbc.username=${DB_USERNAME:postgres}
spring.r2dbc.password=${DB_PASSWORD:zayro}

# JWT Configuration
jwt.secret=${JWT_SECRET:my-super-secret-key-change-this-in-production-with-env-var}
jwt.expiration=${JWT_EXPIRATION:86400000}


# PROFILES
## # Default profile for local development; override to prod in deployment.
spring.profiles.active=dev
